name: animated_cursor
description: '''The "Animated Cursor" package is a Flutter package designed to enhance user interface interactions by providing a visually appealing animated cursor. It offers a customizable animated cursor widget that developers can easily integrate into their Flutter applications. With this package, developers can customize various properties of the cursor, such as color, shape, duration of animations, and border width, to match the design and style of their applications.

Key features of the "Animated Cursor" package include:

Customizable Cursor: Developers can customize the appearance of the cursor by specifying properties such as circle color, dot color, background color, border width, and shape (circle or rectangle).

Animation Control: The package allows developers to control the duration of animations for both the animated circle and dot, providing flexibility in creating smooth and visually appealing cursor effects.

Seamless Integration: The cursor widget provided by the package can be seamlessly integrated into existing Flutter applications, enabling developers to enhance user interactions without significant changes to their codebase.

Overall, the "Animated Cursor" package offers an easy-to-use solution for implementing animated cursors in Flutter applications, enhancing user experience and visual feedback during interactions.
'''
version: 0.0.1
homepage: https://github.com/DarshakDesai199/animated_cursor

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
